name: Test coverage report
on:
  workflow_dispatch:  
  push:
    branches:
      - release/*

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Run tests
        run: mvn -B verify -P coverage --no-transfer-progress
      - name: Upload jacoco coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
          token: ${{ secrets.CODECOV_TOKEN }}
          
          
